<?php

namespace Database\Seeders;

use App\Models\Server;
use Illuminate\Database\Seeder;

class ServerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $servers = [
            // Ubuntu Servers (10)
            [
                'name' => 'ubuntu-web-01',
                'host' => '192.168.1.10',
                'os' => 'Ubuntu',
                'status' => 'Online',
                'description' => 'Primary web server running Ubuntu 22.04 LTS',
                'port' => 22,
                'username' => 'ubuntu',
            ],
            [
                'name' => 'ubuntu-api-01',
                'host' => '192.168.1.11',
                'os' => 'Ubuntu',
                'status' => 'Online',
                'description' => 'API server for production services',
                'port' => 22,
                'username' => 'ubuntu',
            ],
            [
                'name' => 'ubuntu-db-01',
                'host' => '192.168.1.12',
                'os' => 'Ubuntu',
                'status' => 'Online',
                'description' => 'PostgreSQL database server',
                'port' => 22,
                'username' => 'ubuntu',
            ],
            [
                'name' => 'ubuntu-cache-01',
                'host' => '192.168.1.13',
                'os' => 'Ubuntu',
                'status' => 'Online',
                'description' => 'Redis cache server',
                'port' => 22,
                'username' => 'ubuntu',
            ],
            [
                'name' => 'ubuntu-queue-01',
                'host' => '192.168.1.14',
                'os' => 'Ubuntu',
                'status' => 'Online',
                'description' => 'Queue worker server',
                'port' => 22,
                'username' => 'ubuntu',
            ],
            [
                'name' => 'ubuntu-staging-01',
                'host' => '192.168.1.15',
                'os' => 'Ubuntu',
                'status' => 'Offline',
                'description' => 'Staging environment server',
                'port' => 22,
                'username' => 'ubuntu',
            ],
            [
                'name' => 'ubuntu-dev-01',
                'host' => '192.168.1.16',
                'os' => 'Ubuntu',
                'status' => 'Online',
                'description' => 'Development server',
                'port' => 22,
                'username' => 'ubuntu',
            ],
            [
                'name' => 'ubuntu-monitor-01',
                'host' => '192.168.1.17',
                'os' => 'Ubuntu',
                'status' => 'Online',
                'description' => 'Monitoring and logging server',
                'port' => 22,
                'username' => 'ubuntu',
            ],
            [
                'name' => 'ubuntu-backup-01',
                'host' => '192.168.1.18',
                'os' => 'Ubuntu',
                'status' => 'Online',
                'description' => 'Backup storage server',
                'port' => 22,
                'username' => 'ubuntu',
            ],
            [
                'name' => 'ubuntu-vpn-01',
                'host' => '192.168.1.19',
                'os' => 'Ubuntu',
                'status' => 'Online',
                'description' => 'VPN gateway server',
                'port' => 22,
                'username' => 'ubuntu',
            ],

            // Debian Servers (10)
            [
                'name' => 'debian-web-01',
                'host' => '192.168.2.10',
                'os' => 'Debian',
                'status' => 'Online',
                'description' => 'Web server running Debian 12',
                'port' => 22,
                'username' => 'debian',
            ],
            [
                'name' => 'debian-mail-01',
                'host' => '192.168.2.11',
                'os' => 'Debian',
                'status' => 'Online',
                'description' => 'Email server with Postfix',
                'port' => 22,
                'username' => 'debian',
            ],
            [
                'name' => 'debian-dns-01',
                'host' => '192.168.2.12',
                'os' => 'Debian',
                'status' => 'Online',
                'description' => 'Primary DNS server',
                'port' => 22,
                'username' => 'debian',
            ],
            [
                'name' => 'debian-proxy-01',
                'host' => '192.168.2.13',
                'os' => 'Debian',
                'status' => 'Online',
                'description' => 'Reverse proxy with Nginx',
                'port' => 22,
                'username' => 'debian',
            ],
            [
                'name' => 'debian-file-01',
                'host' => '192.168.2.14',
                'os' => 'Debian',
                'status' => 'Online',
                'description' => 'File storage server',
                'port' => 22,
                'username' => 'debian',
            ],
            [
                'name' => 'debian-git-01',
                'host' => '192.168.2.15',
                'os' => 'Debian',
                'status' => 'Online',
                'description' => 'GitLab server',
                'port' => 22,
                'username' => 'git',
            ],
            [
                'name' => 'debian-docker-01',
                'host' => '192.168.2.16',
                'os' => 'Debian',
                'status' => 'Offline',
                'description' => 'Docker host server',
                'port' => 22,
                'username' => 'debian',
            ],
            [
                'name' => 'debian-build-01',
                'host' => '192.168.2.17',
                'os' => 'Debian',
                'status' => 'Online',
                'description' => 'CI/CD build server',
                'port' => 22,
                'username' => 'debian',
            ],
            [
                'name' => 'debian-metrics-01',
                'host' => '192.168.2.18',
                'os' => 'Debian',
                'status' => 'Online',
                'description' => 'Prometheus metrics server',
                'port' => 22,
                'username' => 'debian',
            ],
            [
                'name' => 'debian-logs-01',
                'host' => '192.168.2.19',
                'os' => 'Debian',
                'status' => 'Online',
                'description' => 'Elasticsearch logs server',
                'port' => 22,
                'username' => 'debian',
            ],

            // CentOS Servers (10)
            [
                'name' => 'centos-app-01',
                'host' => '192.168.3.10',
                'os' => 'CentOS',
                'status' => 'Online',
                'description' => 'Application server running CentOS 9',
                'port' => 22,
                'username' => 'centos',
            ],
            [
                'name' => 'centos-db-01',
                'host' => '192.168.3.11',
                'os' => 'CentOS',
                'status' => 'Online',
                'description' => 'MySQL database server',
                'port' => 22,
                'username' => 'centos',
            ],
            [
                'name' => 'centos-load-01',
                'host' => '192.168.3.12',
                'os' => 'CentOS',
                'status' => 'Online',
                'description' => 'Load balancer with HAProxy',
                'port' => 22,
                'username' => 'centos',
            ],
            [
                'name' => 'centos-nfs-01',
                'host' => '192.168.3.13',
                'os' => 'CentOS',
                'status' => 'Online',
                'description' => 'NFS storage server',
                'port' => 22,
                'username' => 'centos',
            ],
            [
                'name' => 'centos-ldap-01',
                'host' => '192.168.3.14',
                'os' => 'CentOS',
                'status' => 'Online',
                'description' => 'LDAP authentication server',
                'port' => 22,
                'username' => 'centos',
            ],
            [
                'name' => 'centos-ftp-01',
                'host' => '192.168.3.15',
                'os' => 'CentOS',
                'status' => 'Offline',
                'description' => 'FTP server',
                'port' => 22,
                'username' => 'centos',
            ],
            [
                'name' => 'centos-firewall-01',
                'host' => '192.168.3.16',
                'os' => 'CentOS',
                'status' => 'Online',
                'description' => 'Firewall server',
                'port' => 22,
                'username' => 'centos',
            ],
            [
                'name' => 'centos-ansible-01',
                'host' => '192.168.3.17',
                'os' => 'CentOS',
                'status' => 'Online',
                'description' => 'Ansible control node',
                'port' => 22,
                'username' => 'centos',
            ],
            [
                'name' => 'centos-jenkins-01',
                'host' => '192.168.3.18',
                'os' => 'CentOS',
                'status' => 'Online',
                'description' => 'Jenkins automation server',
                'port' => 22,
                'username' => 'centos',
            ],
            [
                'name' => 'centos-vault-01',
                'host' => '192.168.3.19',
                'os' => 'CentOS',
                'status' => 'Online',
                'description' => 'HashiCorp Vault server',
                'port' => 22,
                'username' => 'centos',
            ],

            // Windows Servers (10)
            [
                'name' => 'win-dc-01',
                'host' => '192.168.4.10',
                'os' => 'Windows',
                'status' => 'Online',
                'description' => 'Primary domain controller',
                'port' => 3389,
                'username' => 'administrator',
            ],
            [
                'name' => 'win-sql-01',
                'host' => '192.168.4.11',
                'os' => 'Windows',
                'status' => 'Online',
                'description' => 'SQL Server 2022',
                'port' => 3389,
                'username' => 'administrator',
            ],
            [
                'name' => 'win-iis-01',
                'host' => '192.168.4.12',
                'os' => 'Windows',
                'status' => 'Online',
                'description' => 'IIS web server',
                'port' => 3389,
                'username' => 'administrator',
            ],
            [
                'name' => 'win-exchange-01',
                'host' => '192.168.4.13',
                'os' => 'Windows',
                'status' => 'Online',
                'description' => 'Exchange mail server',
                'port' => 3389,
                'username' => 'administrator',
            ],
            [
                'name' => 'win-file-01',
                'host' => '192.168.4.14',
                'os' => 'Windows',
                'status' => 'Online',
                'description' => 'File server',
                'port' => 3389,
                'username' => 'administrator',
            ],
            [
                'name' => 'win-print-01',
                'host' => '192.168.4.15',
                'os' => 'Windows',
                'status' => 'Offline',
                'description' => 'Print server',
                'port' => 3389,
                'username' => 'administrator',
            ],
            [
                'name' => 'win-rds-01',
                'host' => '192.168.4.16',
                'os' => 'Windows',
                'status' => 'Online',
                'description' => 'Remote desktop services',
                'port' => 3389,
                'username' => 'administrator',
            ],
            [
                'name' => 'win-backup-01',
                'host' => '192.168.4.17',
                'os' => 'Windows',
                'status' => 'Online',
                'description' => 'Backup server with Veeam',
                'port' => 3389,
                'username' => 'administrator',
            ],
            [
                'name' => 'win-app-01',
                'host' => '192.168.4.18',
                'os' => 'Windows',
                'status' => 'Online',
                'description' => 'Application server',
                'port' => 3389,
                'username' => 'administrator',
            ],
            [
                'name' => 'win-wsus-01',
                'host' => '192.168.4.19',
                'os' => 'Windows',
                'status' => 'Online',
                'description' => 'WSUS update server',
                'port' => 3389,
                'username' => 'administrator',
            ],

            // Other Servers (10)
            [
                'name' => 'freebsd-router-01',
                'host' => '192.168.5.10',
                'os' => 'Other',
                'status' => 'Online',
                'description' => 'FreeBSD router',
                'port' => 22,
                'username' => 'root',
            ],
            [
                'name' => 'openbsd-fw-01',
                'host' => '192.168.5.11',
                'os' => 'Other',
                'status' => 'Online',
                'description' => 'OpenBSD firewall',
                'port' => 22,
                'username' => 'root',
            ],
            [
                'name' => 'alpine-container-01',
                'host' => '192.168.5.12',
                'os' => 'Other',
                'status' => 'Online',
                'description' => 'Alpine Linux container host',
                'port' => 22,
                'username' => 'alpine',
            ],
            [
                'name' => 'arch-dev-01',
                'host' => '192.168.5.13',
                'os' => 'Other',
                'status' => 'Offline',
                'description' => 'Arch Linux development server',
                'port' => 22,
                'username' => 'arch',
            ],
            [
                'name' => 'fedora-test-01',
                'host' => '192.168.5.14',
                'os' => 'Other',
                'status' => 'Online',
                'description' => 'Fedora testing server',
                'port' => 22,
                'username' => 'fedora',
            ],
            [
                'name' => 'suse-enterprise-01',
                'host' => '192.168.5.15',
                'os' => 'Other',
                'status' => 'Online',
                'description' => 'SUSE Linux Enterprise',
                'port' => 22,
                'username' => 'suse',
            ],
            [
                'name' => 'oracle-db-01',
                'host' => '192.168.5.16',
                'os' => 'Other',
                'status' => 'Online',
                'description' => 'Oracle Linux database',
                'port' => 22,
                'username' => 'oracle',
            ],
            [
                'name' => 'rocky-app-01',
                'host' => '192.168.5.17',
                'os' => 'Other',
                'status' => 'Online',
                'description' => 'Rocky Linux application server',
                'port' => 22,
                'username' => 'rocky',
            ],
            [
                'name' => 'alma-web-01',
                'host' => '192.168.5.18',
                'os' => 'Other',
                'status' => 'Online',
                'description' => 'AlmaLinux web server',
                'port' => 22,
                'username' => 'alma',
            ],
            [
                'name' => 'nixos-infra-01',
                'host' => '192.168.5.19',
                'os' => 'Other',
                'status' => 'Online',
                'description' => 'NixOS infrastructure server',
                'port' => 22,
                'username' => 'nixos',
            ],
        ];

        foreach ($servers as $server) {
            Server::create($server);
        }
    }
}
